import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/surface-state";
import {
  DIGEST_RECORD_PREFIX,
  isPublishedDigest,
  type WeeklyDigestRecord as WeeklyDigest,
} from "@/lib/community-agent";
import { getDigest } from "@/lib/i18n/dictionaries";
import { getEnv } from "@/lib/kv";
import { buildPageMetadata } from "@/lib/page-meta";

type DigestSection = WeeklyDigest["sections"][number];

export const revalidate = 3600; // Cache page updates hourly

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = getDigest(locale);
  return buildPageMetadata({
    path: "/digest",
    locale,
    title: t.metaTitle,
    description: t.metaDescription,
  });
}

export default async function DigestArchivePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = getDigest(locale);

  // 1. Get the correct project environment bindings
  const env = await getEnv();
  const kv = env.CURATED_KV;

  // Fallback array if no data is found or if KV isn't active in dev
  let digests: WeeklyDigest[] = [];

  if (kv) {
    try {
      // Fetch all weekly digest keys generated by the agent tasks
      const { keys } = await kv.list({ prefix: DIGEST_RECORD_PREFIX });

      if (keys && keys.length > 0) {
        const digestsRaw = await Promise.all(
          keys.map(async (k: { name: string }) => {
            const data = await kv.get(k.name);
            return data;
          })
        );

        // Parse each entry independently so a single malformed record can't
        // blank the entire archive — skip only the bad ones. The cron stages
        // records unapproved; only maintainer-approved ones are public.
        digests = digestsRaw
          .filter((item: string | null): item is string => Boolean(item))
          .flatMap((item: string) => {
            try {
              const parsed: unknown = JSON.parse(item);
              return isPublishedDigest(parsed) ? [parsed] : [];
            } catch (e) {
              console.error("Skipping malformed digest entry:", e);
              return [];
            }
          })
          .sort((a: WeeklyDigest, b: WeeklyDigest) =>
            new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
          );
      }
    } catch (e) {
      console.error("Error reading from KV:", e);
    }
  }

  // A maintainer reviews a digest in one language (the admin locale), and
  // only that language is published, so each digest renders in the language
  // it was reviewed in whatever the reader's locale.

  if (digests.length === 0) {
    return (
      <>
        <PageHeader title={t.title} lede={t.lead} pose="read" />
        <div className="page-body">
          <EmptyState locale={locale} title={t.emptyTitle} body={t.emptyBody} pose="sleep" />
        </div>
      </>
    );
  }

  return (
    <>
      <PageHeader title={t.title} lede={t.lead} pose="read" />
      <div className="page-body">
        <div className="page-body-narrow digest-list">
          {digests.map((digest: WeeklyDigest) => {
            const zh = digest.approvedLang === "zh";
            return (
            <article key={digest.weekId} className="changelog-release" lang={zh ? "zh" : "en"}>
              <header className="digest-head">
                <span className="pill tabular">{digest.weekId}</span>
                <h2 className="section-title">{zh ? digest.titleZh : digest.titleEn}</h2>
                <p className="section-scope">{zh ? digest.summaryZh : digest.summaryEn}</p>
              </header>
              <div className="changelog-sections">
                {digest.sections.map((section: DigestSection, idx: number) => (
                  <section key={idx}>
                    <h3>{section.heading}</h3>
                    <ul>
                      {section.items.map((item: string, itemIdx: number) => (
                        <li key={itemIdx}>{item}</li>
                      ))}
                    </ul>
                  </section>
                ))}
              </div>
            </article>
            );
          })}
        </div>
      </div>
    </>
  );
}
