import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/surface-state";
import { getDigest, pickTextLocale } from "@/lib/i18n/dictionaries";
import { getEnv } from "@/lib/kv";
import { buildPageMetadata } from "@/lib/page-meta";

// Define the exact structure of the Digest data to fix all the 'any' type errors
interface DigestSection {
  heading: string;
  items: string[];
}

interface WeeklyDigest {
  weekId: string;
  titleEn: string;
  titleZh: string;
  summaryEn: string;
  summaryZh: string;
  sections: DigestSection[];
  generatedAt: string;
}

export const revalidate = 3600; // Cache page updates hourly

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = getDigest(locale);
  return buildPageMetadata({
    path: "/digest",
    locale,
    title: t.metaTitle,
    description: t.metaDescription,
  });
}

export default async function DigestArchivePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = getDigest(locale);

  // 1. Get the correct project environment bindings
  const env = await getEnv();
  const kv = env.CURATED_KV;

  // Fallback array if no data is found or if KV isn't active in dev
  let digests: WeeklyDigest[] = [];

  if (kv) {
    try {
      // Fetch all weekly digest keys generated by the agent tasks
      const { keys } = await kv.list({ prefix: "digest:weekly-" });

      if (keys && keys.length > 0) {
        const digestsRaw = await Promise.all(
          keys.map(async (k: { name: string }) => {
            const data = await kv.get(k.name);
            return data;
          })
        );

        // Parse each entry independently so a single malformed record can't
        // blank the entire archive — skip only the bad ones.
        digests = digestsRaw
          .filter((item: string | null): item is string => Boolean(item))
          .flatMap((item: string) => {
            try {
              return [JSON.parse(item) as WeeklyDigest];
            } catch (e) {
              console.error("Skipping malformed digest entry:", e);
              return [];
            }
          })
          .sort((a: WeeklyDigest, b: WeeklyDigest) =>
            new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
          );
      }
    } catch (e) {
      console.error("Error reading from KV:", e);
    }
  }

  // The records are bilingual; show the reader's language (English for
  // every locale without a Chinese record).
  const zh = pickTextLocale(locale) === "zh";

  if (digests.length === 0) {
    return (
      <>
        <PageHeader title={t.title} lede={t.lead} pose="read" />
        <div className="page-body">
          <EmptyState locale={locale} title={t.emptyTitle} body={t.emptyBody} pose="sleep" />
        </div>
      </>
    );
  }

  return (
    <>
      <PageHeader title={t.title} lede={t.lead} pose="read" />
      <div className="page-body">
        <div className="page-body-narrow digest-list">
          {digests.map((digest: WeeklyDigest) => (
            <article key={digest.weekId} className="changelog-release" lang={zh ? "zh" : "en"}>
              <header className="digest-head">
                <span className="pill tabular">{digest.weekId}</span>
                <h2 className="section-title">{zh ? digest.titleZh : digest.titleEn}</h2>
                <p className="section-scope">{zh ? digest.summaryZh : digest.summaryEn}</p>
              </header>
              <div className="changelog-sections">
                {digest.sections.map((section: DigestSection, idx: number) => (
                  <section key={idx}>
                    <h3>{section.heading}</h3>
                    <ul>
                      {section.items.map((item: string, itemIdx: number) => (
                        <li key={itemIdx}>{item}</li>
                      ))}
                    </ul>
                  </section>
                ))}
              </div>
            </article>
          ))}
        </div>
      </div>
    </>
  );
}
