import type { KeyObject } from "node:crypto";
import type { CloudFactsEnvelope } from "../lib/cloud-facts";
import type { TrustedKey } from "../lib/cloud-facts/keys";
export const MAX_ENVELOPE_BYTES: number;
export function verifyEnvelope(envelope: unknown, publicKeyB64: string): { ok: boolean; errors: string[]; payload?: Record<string, unknown>; sha256?: string };
export function validateSource(source: unknown): string[];
export function parseTsKeys(text: string): TrustedKey[];
export function validateTrustedKeys(keys: readonly TrustedKey[]): readonly TrustedKey[];
export function activePublishingKey(envelope: CloudFactsEnvelope, keys: readonly TrustedKey[], now?: number): { key: TrustedKey; check: ReturnType<typeof verifyEnvelope> };
export function emitSql(envelope: unknown, options: { publishedBy?: string; publicKeyB64: string; notes?: string }): string;
export function readBoundedFile(path: string, maxBytes?: number): Buffer;
export function readBoundedResponse(response: Response, maxBytes?: number): Promise<string>;
export function buildEnvelope(options: { privateKey: KeyObject; keyId: string; payload: Record<string, unknown> }): CloudFactsEnvelope;
export type PostgrestRequest = (path: string, init?: { method?: string; body?: Record<string, unknown>; prefer?: string }) => Promise<unknown>;
export function publishRelease(request: PostgrestRequest, envelope: CloudFactsEnvelope, row: Record<string, unknown>, publicKey: string): Promise<Record<string, unknown>>;
export function revokeRelease(request: PostgrestRequest, options: { channel: string; version: number; reason: string; at: string }): Promise<Record<string, unknown>>;
