// Build the single-file host bundle that the Rust binary embeds.
//
// `dist/` is committed so `cargo build` never needs Node or npm; CI rebuilds
// and fails on drift (`git diff --exit-code dist`).
import { build } from 'esbuild'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const outdir = join(here, 'dist')
mkdirSync(outdir, { recursive: true })

await build({
  entryPoints: [join(here, 'src/main.ts')],
  outfile: join(outdir, 'codewhale-extension-host.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  // Deterministic output: no sourcemap paths, no timestamps, no minification
  // (a readable bundle keeps the reviewed-bytes story honest).
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  banner: {
    js: '// codewhale-extension-host — generated by crates/tui/extension-host/build.mjs; do not edit.\n// Third-party notices: LICENSES.txt next to this file.',
  },
})

// Test-only protocol module (codec + validators) so `node --test` can check
// the corpus against the exact code the host runs, without booting a host.
// Not embedded in the Rust binary.
await build({
  entryPoints: [join(here, 'src/protocol.ts')],
  outfile: join(outdir, 'protocol.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  banner: { js: '// generated by crates/tui/extension-host/build.mjs from src/protocol.ts; do not edit.' },
})

// Third-party notices for everything bundled.
const bundled = [
  '@deepseek-ai/cordis',
  '@deepseek-ai/schemastery',
  '@deepseek-ai/cosmokit',
  '@deepseek-ai/dsh-util-values',
  '@standard-schema/spec',
]
const sections = [
  'Third-party software bundled into codewhale-extension-host.mjs.',
  '',
  'src/dsh/dsh-tools-compat.js also contains verbatim excerpts of',
  '@deepseek-ai/dsh-tools@0.1.7-alpha.2 (MIT, Copyright (c) 2026 DeepSeek),',
  'under the same license text as @deepseek-ai/dsh-util-values below.',
]
for (const name of bundled) {
  const root = join(here, 'node_modules', name)
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
  let license = ''
  for (const file of ['LICENSE', 'LICENSE.md', 'license']) {
    try {
      license = readFileSync(join(root, file), 'utf8').trim()
      break
    } catch {}
  }
  sections.push('', '='.repeat(72), `${pkg.name}@${pkg.version} (${pkg.license})`, '='.repeat(72), '', license || `License: ${pkg.license}`)
}
writeFileSync(join(outdir, 'LICENSES.txt'), sections.join('\n') + '\n')
