//! Workflow configuration schema.
//!
//! The model generates a [`WorkflowConfig`] JSON document that describes
//! the phases, tasks, dependencies, and concurrency constraints. The
//! scheduler reads this config and executes it.

use serde::{Deserialize, Serialize};

/// Top-level workflow configuration generated by the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkflowConfig {
    /// Human-readable goal for the workflow run.
    pub goal: String,

    /// Maximum concurrent agents across all phases.
    /// Default: 6. Hard ceiling enforced by the scheduler.
    #[serde(default = "default_max_concurrent")]
    pub max_concurrent: usize,

    /// Ordered list of phases. Phases without explicit `depends_on`
    /// run in declaration order.
    pub phases: Vec<Phase>,
}

/// A phase is a group of tasks that share the same dependency boundary.
///
/// All tasks within a phase can run concurrently (up to `max_concurrent`).
/// The phase completes when all its tasks have finished or been skipped.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Phase {
    /// Display name for progress reporting.
    pub name: String,

    /// Phases this phase depends on. The scheduler topologically sorts
    /// phases so that dependencies complete before this phase starts.
    #[serde(default)]
    pub depends_on: Vec<String>,

    /// If true, all tasks in this phase run concurrently.
    /// If false, tasks run sequentially.
    #[serde(default = "default_true")]
    pub parallel: bool,

    /// Failure policy for this phase.
    #[serde(default)]
    pub on_failure: FailurePolicy,

    /// Tasks in this phase.
    pub tasks: Vec<Task>,
}

/// How the scheduler handles task failures within a phase.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FailurePolicy {
    /// Skip the failed task. Continue with remaining tasks.
    /// Downstream tasks that depend on the failed task get skipped.
    #[default]
    SkipContinue,

    /// Abort the entire workflow immediately on any failure.
    Abort,
}

/// Whether a task only reads or also writes files.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TaskMode {
    /// Task only reads files (discovery, audit, review, research).
    /// Any number of read-only tasks can run in parallel safely.
    #[default]
    ReadOnly,
    /// Task may write files. The scheduler uses `file_scope` to detect
    /// conflicts with other concurrent write tasks.
    ReadWrite,
}

/// How the agent is isolated from the main workspace.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum IsolationMode {
    /// Agent works directly in the main workspace (default).
    /// File-scope conflict detection prevents overlapping writes.
    #[default]
    Shared,
    /// Agent runs in a dedicated git worktree. No conflict risk.
    /// The scheduler creates and cleans up the worktree automatically.
    Worktree,
}

impl IsolationMode {
    /// Return the working directory for this isolation mode.
    ///
    /// `Shared` tasks run in the main workspace (None = use default).
    /// `Worktree` tasks get a dedicated directory under `.worktrees/`.
    /// The caller (scheduler or spawner) passes the task id so the path
    /// is deterministic: `.worktrees/whaleflow-{task_id}`.
    pub fn cwd_path(&self, task_id: &str) -> Option<std::path::PathBuf> {
        match self {
            IsolationMode::Shared => None,
            IsolationMode::Worktree => {
                Some(std::path::PathBuf::from(format!(".worktrees/whaleflow-{}", task_id)))
            }
        }
    }
}

/// A single unit of work assigned to one agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Task {
    /// Unique identifier within the workflow (e.g. "scan-auth").
    pub id: String,

    /// Prompt sent to the sub-agent.
    pub prompt: String,

    /// Sub-agent type: "explore", "review", "implementer", "verifier", or
    /// `None` for the default type.
    #[serde(default)]
    pub agent_type: Option<String>,

    /// Tasks whose results should be injected into this task's prompt
    /// as context. Used for cross-phase data flow.
    #[serde(default)]
    pub depends_on_results: Vec<String>,

    /// Maximum steps the agent may take. Maps to `max_depth` on `agent_open`.
    #[serde(default)]
    pub max_steps: Option<u32>,

    /// Timeout for this specific task in seconds.
    #[serde(default)]
    pub timeout_secs: Option<u64>,

    /// Whether the task reads only or may write files.
    /// Scheduler uses this for conflict detection in parallel phases.
    #[serde(default)]
    pub mode: TaskMode,

    /// File glob patterns the task is scoped to (e.g. `["src/auth/**"]`).
    /// Required for `ReadWrite` tasks in parallel phases.
    /// Scheduler detects overlapping scopes and serializes or warns.
    #[serde(default)]
    pub file_scope: Vec<String>,

    /// Isolation strategy for this agent.
    #[serde(default)]
    pub isolation: IsolationMode,
}

fn default_max_concurrent() -> usize {
    6
}

fn default_true() -> bool {
    true
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

impl WorkflowConfig {
    /// Validate the config for structural correctness.
    ///
    /// Returns `Ok(())` if the config is valid, or a list of errors.
    pub fn validate(&self) -> Result<(), Vec<String>> {
        let mut errors: Vec<String> = Vec::new();

        // Phases must exist.
        if self.phases.is_empty() {
            errors.push("at least one phase is required".into());
        }

        // Every phase must have at least one task.
        for phase in &self.phases {
            if phase.tasks.is_empty() {
                errors.push(format!("phase '{}' has no tasks", phase.name));
            }
        }

        // Task IDs must be unique across the entire workflow.
        let mut seen_ids = std::collections::HashSet::new();
        for phase in &self.phases {
            for task in &phase.tasks {
                if !seen_ids.insert(&task.id) {
                    errors.push(format!("duplicate task id '{}'", task.id));
                }
            }
        }

        // `depends_on` must reference valid phase names.
        for phase in &self.phases {
            for dep in &phase.depends_on {
                if dep == &phase.name {
                    errors.push(format!(
                        "phase '{}' depends on itself",
                        phase.name
                    ));
                }
                if !self.phases.iter().any(|p| &p.name == dep) {
                    errors.push(format!(
                        "phase '{}' depends on unknown phase '{}'",
                        phase.name, dep
                    ));
                }
            }
        }

        // `depends_on_results` must reference valid task IDs.
        for phase in &self.phases {
            for task in &phase.tasks {
                for dep in &task.depends_on_results {
                    if !seen_ids.contains(dep) {
                        errors.push(format!(
                            "task '{}' depends on unknown task result '{}'",
                            task.id, dep
                        ));
                    }
                }
            }
        }

        // ReadWrite tasks in parallel phases must declare file_scope
        // (unless they use worktree isolation).
        for phase in &self.phases {
            if !phase.parallel || phase.tasks.len() < 2 {
                continue;
            }
            for task in &phase.tasks {
                if task.mode == TaskMode::ReadWrite
                    && task.isolation != IsolationMode::Worktree
                    && task.file_scope.is_empty()
                {
                    errors.push(format!(
                        "task '{}' is ReadWrite with no file_scope in parallel phase '{}'. \
                         Add file_scope, use isolation 'worktree', or make the phase sequential.",
                        task.id, phase.name
                    ));
                }
            }
        }

        // Detect cycles in phase dependencies.
        if let Some(cycle) = detect_cycle(&self.phases) {
            errors.push(format!(
                "cycle detected in phase dependencies: {}",
                cycle.join(" -> ")
            ));
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    /// Detect file-scope conflicts among `ReadWrite` tasks in parallel phases.
    ///
    /// Returns a list of conflict descriptions. An empty list means no
    /// overlapping scopes were detected. `Worktree`-isolated tasks are
    /// exempt from conflict detection.
    pub fn detect_conflicts(&self) -> Vec<Conflict> {
        let mut conflicts: Vec<Conflict> = Vec::new();

        for phase in &self.phases {
            if !phase.parallel || phase.tasks.len() < 2 {
                continue;
            }

            let write_tasks: Vec<&Task> = phase
                .tasks
                .iter()
                .filter(|t| t.mode == TaskMode::ReadWrite && t.isolation != IsolationMode::Worktree)
                .collect();

            // Each ReadWrite task must declare a file_scope in a parallel phase.
            for task in &write_tasks {
                if task.file_scope.is_empty() {
                    conflicts.push(Conflict {
                        kind: ConflictKind::MissingFileScope,
                        phase: phase.name.clone(),
                        task_a: task.id.clone(),
                        task_b: String::new(),
                        description: format!(
                            "task '{}' is ReadWrite with no file_scope in parallel phase '{}'. \
                             Add file_scope, set isolation to 'worktree', or make the phase sequential.",
                            task.id, phase.name
                        ),
                    });
                }
            }

            // Check for overlapping scopes between pairs of write tasks.
            for i in 0..write_tasks.len() {
                for j in (i + 1)..write_tasks.len() {
                    let a = write_tasks[i];
                    let b = write_tasks[j];

                    if scopes_overlap(&a.file_scope, &b.file_scope) {
                        conflicts.push(Conflict {
                            kind: ConflictKind::OverlappingScopes,
                            phase: phase.name.clone(),
                            task_a: a.id.clone(),
                            task_b: b.id.clone(),
                            description: format!(
                                "tasks '{}' and '{}' have overlapping file scopes in parallel \
                                 phase '{}'. Use 'worktree' isolation, disjoint scopes, or \
                                 make the phase sequential.",
                                a.id, b.id, phase.name
                            ),
                        });
                    }
                }
            }
        }

        conflicts
    }
}

/// A conflict detected during validation.
#[derive(Debug, Clone)]
pub struct Conflict {
    pub kind: ConflictKind,
    pub phase: String,
    pub task_a: String,
    pub task_b: String,
    pub description: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConflictKind {
    /// A ReadWrite task in a parallel phase has no file_scope.
    MissingFileScope,
    /// Two ReadWrite tasks have overlapping file scopes.
    OverlappingScopes,
}

impl Conflict {
    /// Human-readable name for the conflict kind.
    pub fn kind_name(&self) -> &'static str {
        match self.kind {
            ConflictKind::MissingFileScope => "missing_file_scope",
            ConflictKind::OverlappingScopes => "overlapping_scopes",
        }
    }
}

/// Check if two sets of file scope patterns overlap.
///
/// Uses prefix matching: strips glob suffixes (`/**`, `/*`) and checks
/// if one prefix starts with the other. Simple but effective for the
/// typical patterns the model generates (e.g. `src/auth/**`).
fn scopes_overlap(a: &[String], b: &[String]) -> bool {
    if a.is_empty() || b.is_empty() {
        return false;
    }

    fn strip_glob(s: &str) -> &str {
        s.trim_end_matches('/')
            .trim_end_matches("**")
            .trim_end_matches('*')
            .trim_end_matches('/')
    }

    let a_prefixes: Vec<&str> = a.iter().map(|s| strip_glob(s)).collect();
    let b_prefixes: Vec<&str> = b.iter().map(|s| strip_glob(s)).collect();

    for ap in &a_prefixes {
        for bp in &b_prefixes {
            if ap.starts_with(bp) || bp.starts_with(ap) {
                return true;
            }
        }
    }

    false
}

/// Simple cycle detection via DFS.
fn detect_cycle(phases: &[Phase]) -> Option<Vec<String>> {
    use std::collections::{HashMap, HashSet};

    let phase_names: HashSet<&str> = phases.iter().map(|p| p.name.as_str()).collect();

    // Build adjacency: phase -> phases it depends on
    let mut edges: HashMap<&str, Vec<&str>> = HashMap::new();
    for phase in phases {
        let deps: Vec<&str> = phase
            .depends_on
            .iter()
            .filter(|d| phase_names.contains(d.as_str()))
            .map(|s| s.as_str())
            .collect();
        edges.insert(&phase.name, deps);
    }

    #[derive(Clone, Copy, PartialEq, Eq)]
    enum Color {
        White,
        Gray,
        Black,
    }

    let mut colors: HashMap<&str, Color> = HashMap::new();
    for name in &phase_names {
        colors.insert(name, Color::White);
    }

    fn dfs<'a>(
        node: &'a str,
        edges: &HashMap<&'a str, Vec<&'a str>>,
        colors: &mut HashMap<&'a str, Color>,
        path: &mut Vec<&'a str>,
    ) -> Option<Vec<String>> {
        colors.insert(node, Color::Gray);
        path.push(node);

        if let Some(neighbors) = edges.get(node) {
            for &neighbor in neighbors {
                let color = colors[neighbor];
                if color == Color::Gray {
                    // Found a cycle: extract it from the path.
                    let cycle_start = path.iter().position(|&n| n == neighbor).unwrap();
                    let cycle: Vec<String> = path[cycle_start..]
                        .iter()
                        .map(|s| s.to_string())
                        .collect();
                    return Some(cycle);
                }
                if color == Color::White {
                    if let Some(cycle) = dfs(neighbor, edges, colors, path) {
                        return Some(cycle);
                    }
                }
            }
        }

        path.pop();
        colors.insert(node, Color::Black);
        None
    }

    for name in &phase_names {
        if colors[name] == Color::White {
            let mut path = Vec::new();
            if let Some(cycle) = dfs(name, &edges, &mut colors, &mut path) {
                return Some(cycle);
            }
        }
    }

    None
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_task(id: &str, prompt: &str) -> Task {
        Task {
            id: id.into(),
            prompt: prompt.into(),
            agent_type: None,
            depends_on_results: vec![],
            max_steps: None,
            timeout_secs: None,
            mode: TaskMode::ReadOnly,
            file_scope: vec![],
            isolation: IsolationMode::Shared,
        }
    }

    fn make_write_task(id: &str, prompt: &str, scope: &[&str]) -> Task {
        Task {
            id: id.into(),
            prompt: prompt.into(),
            mode: TaskMode::ReadWrite,
            file_scope: scope.iter().map(|s| s.to_string()).collect(),
            ..make_task(id, prompt)
        }
    }

    #[test]
    fn valid_config_passes() {
        let config = WorkflowConfig {
            goal: "test".into(),
            max_concurrent: 4,
            phases: vec![Phase {
                name: "discovery".into(),
                depends_on: vec![],
                parallel: true,
                on_failure: FailurePolicy::SkipContinue,
                tasks: vec![make_task("scan-1", "scan")],
            }],
        };
        assert!(config.validate().is_ok());
    }

    #[test]
    fn duplicate_task_ids_fail() {
        let config = WorkflowConfig {
            goal: "test".into(),
            max_concurrent: 4,
            phases: vec![
                Phase {
                    name: "a".into(),
                    depends_on: vec![],
                    parallel: true,
                    on_failure: FailurePolicy::SkipContinue,
                    tasks: vec![make_task("dup", "x")],
                },
                Phase {
                    name: "b".into(),
                    depends_on: vec![],
                    parallel: true,
                    on_failure: FailurePolicy::SkipContinue,
                    tasks: vec![make_task("dup", "y")],
                },
            ],
        };
        let err = config.validate().unwrap_err();
        assert!(err.iter().any(|e| e.contains("duplicate")));
    }

    #[test]
    fn cycle_detection() {
        let config = WorkflowConfig {
            goal: "test".into(),
            max_concurrent: 4,
            phases: vec![
                Phase {
                    name: "a".into(),
                    depends_on: vec!["b".into()],
                    parallel: true,
                    on_failure: FailurePolicy::SkipContinue,
                    tasks: vec![make_task("t1", "x")],
                },
                Phase {
                    name: "b".into(),
                    depends_on: vec!["a".into()],
                    parallel: true,
                    on_failure: FailurePolicy::SkipContinue,
                    tasks: vec![make_task("t2", "y")],
                },
            ],
        };
        let err = config.validate().unwrap_err();
        assert!(err.iter().any(|e| e.contains("cycle")));
    }

    #[test]
    fn no_conflicts_for_read_only_tasks() {
        let config = WorkflowConfig {
            goal: "test".into(),
            max_concurrent: 4,
            phases: vec![Phase {
                name: "audit".into(),
                depends_on: vec![],
                parallel: true,
                on_failure: FailurePolicy::SkipContinue,
                tasks: vec![make_task("a", "scan a"), make_task("b", "scan b")],
            }],
        };
        assert!(config.detect_conflicts().is_empty());
    }

    #[test]
    fn missing_file_scope_detected() {
        let config = WorkflowConfig {
            goal: "test".into(),
            max_concurrent: 4,
            phases: vec![Phase {
                name: "fixes".into(),
                depends_on: vec![],
                parallel: true,
                on_failure: FailurePolicy::SkipContinue,
                tasks: vec![
                    make_task("a", "fix a"), // ReadOnly — fine
                    Task {
                        mode: TaskMode::ReadWrite,
                        file_scope: vec![],
                        ..make_task("b", "fix b")
                    }, // ReadWrite, no scope
                ],
            }],
        };
        let conflicts = config.detect_conflicts();
        assert_eq!(conflicts.len(), 1);
        assert_eq!(conflicts[0].kind, ConflictKind::MissingFileScope);
    }

    #[test]
    fn overlapping_scopes_detected() {
        let config = WorkflowConfig {
            goal: "test".into(),
            max_concurrent: 4,
            phases: vec![Phase {
                name: "fixes".into(),
                depends_on: vec![],
                parallel: true,
                on_failure: FailurePolicy::SkipContinue,
                tasks: vec![
                    make_write_task("a", "fix auth", &["src/auth/**"]),
                    make_write_task("b", "fix api", &["src/auth/**"]),
                ],
            }],
        };
        let conflicts = config.detect_conflicts();
        assert_eq!(conflicts.len(), 1);
        assert_eq!(conflicts[0].kind, ConflictKind::OverlappingScopes);
    }

    #[test]
    fn disjoint_scopes_no_conflict() {
        let config = WorkflowConfig {
            goal: "test".into(),
            max_concurrent: 4,
            phases: vec![Phase {
                name: "fixes".into(),
                depends_on: vec![],
                parallel: true,
                on_failure: FailurePolicy::SkipContinue,
                tasks: vec![
                    make_write_task("a", "fix auth", &["src/auth/**"]),
                    make_write_task("b", "fix api", &["src/api/**"]),
                ],
            }],
        };
        assert!(config.detect_conflicts().is_empty());
    }

    #[test]
    fn worktree_tasks_exempt_from_conflicts() {
        let config = WorkflowConfig {
            goal: "test".into(),
            max_concurrent: 4,
            phases: vec![Phase {
                name: "fixes".into(),
                depends_on: vec![],
                parallel: true,
                on_failure: FailurePolicy::SkipContinue,
                tasks: vec![
                    Task {
                        mode: TaskMode::ReadWrite,
                        file_scope: vec!["src/auth/**".into()],
                        isolation: IsolationMode::Worktree,
                        ..make_task("a", "fix auth")
                    },
                    Task {
                        mode: TaskMode::ReadWrite,
                        file_scope: vec!["src/auth/**".into()],
                        isolation: IsolationMode::Worktree,
                        ..make_task("b", "fix auth too")
                    },
                ],
            }],
        };
        assert!(config.detect_conflicts().is_empty());
    }
}
