//! The Codewhale mark, derived from the canonical founder raster by
//! `scripts/brand/braille-mark.py`, and terminal color/capability helpers.
//! The launch header paints the mark as terminal cells; no image is transmitted.

use std::sync::OnceLock;

use ratatui::style::Color;

/// The launch mark resolves once; controls and text never wait for it.
pub(crate) const REVEAL_MS: u128 = 360;

pub(crate) fn reveal_row(row: &str, elapsed_ms: u128, animated: bool) -> String {
    let mask = if !animated || elapsed_ms >= REVEAL_MS {
        0xff
    } else if elapsed_ms < 60 {
        0x09
    } else if elapsed_ms < 140 {
        0x1b
    } else if elapsed_ms < 240 {
        0x3f
    } else {
        0x7f
    };
    row.chars()
        .map(|ch| {
            let code = u32::from(ch);
            if (0x2800..=0x28ff).contains(&code) {
                char::from_u32(0x2800 + ((code - 0x2800) & mask)).unwrap_or(ch)
            } else {
                ch
            }
        })
        .collect()
}

/// Rungs of the mark's scale ladder, each generated at its own box.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MarkSize {
    /// Box 22×6, ink 14×6 — the launch screen's hero mark. Generated from the
    /// same founder raster as the smaller rungs, at a size where the whale
    /// reads as a whale.
    Large,
    /// Box 11×3, ink 7×3 — the launch header's mark.
    Small,
    /// Box 8×2, ink 5×2 — for stages too narrow for the header lines beside
    /// the small rung.
    Tiny,
}

// generated by scripts/brand/braille-mark.py from brand/codewhalemarkfinal.png
// (founder hero whale 504x453px, threshold 0.3, aspect preserved,
// edge columns trimmed, eye carved)

// LARGE: box 22x6 -> ink 14x6
const LARGE_ROWS: [&str; 6] = [
    "  ⣀⣴⣶⣾⣶⣆      ",
    "⢀⣼⣿⠛⠉⠉⠙⠻⠟⠃    ",
    "⢸⣿⡇    ⢀⣀⣤⣤⣤⣤⡀",
    "⢸⣿⣷⣤⣤⣶⣿⣿⣿⡿⠟⠉⣹⠁",
    "⠈⢻⣿⣿⣿⣿⣿⣷⠟ ⢀⡴⠁ ",
    "  ⠈⠉⠽⠿⣿⠥⠤⠒⠉   ",
];

// SMALL: box 11x3 -> ink 7x3
const SMALL_ROWS: [&str; 3] = [
    "⢠⡶⠛⠧⠄  ", //
    "⣿⣄⣠⣤⣶⠶⠆",
    "⠘⠻⣿⣗⠡⠊ ",
];

// TINY: box 8x2 -> ink 5x2
const TINY_ROWS: [&str; 2] = [
    "⢠⡞⠛⢂⣀", //
    "⠘⠿⣿⠍⠉",
];

impl MarkSize {
    /// Cell footprint as `(cols, rows)` — the ink's, not the design box's.
    #[must_use]
    pub const fn cells(self) -> (u16, u16) {
        match self {
            Self::Large => (14, 6),
            Self::Small => (7, 3),
            Self::Tiny => (5, 2),
        }
    }

    /// The braille rows for this rung. Blank cells are spaces so the
    /// renderer leaves the field behind them untouched.
    #[must_use]
    pub const fn rows(self) -> &'static [&'static str] {
        match self {
            Self::Large => &LARGE_ROWS,
            Self::Small => &SMALL_ROWS,
            Self::Tiny => &TINY_ROWS,
        }
    }
}

/// Blend `from` toward `to` (0.0 → `from`, 1.0 → `to`). At 0 the mark is
/// exactly the field colour, so it rises out of the water rather than over it.
#[must_use]
pub fn lerp_color(from: Color, to: Color, amount: f32) -> Color {
    let amount = amount.clamp(0.0, 1.0);
    match (from, to) {
        (Color::Rgb(fr, fg, fb), Color::Rgb(tr, tg, tb)) => Color::Rgb(
            lerp_channel(fr, tr, amount),
            lerp_channel(fg, tg, amount),
            lerp_channel(fb, tb, amount),
        ),
        // Indexed colours have no channels to interpolate; snap at midpoint.
        _ => {
            if amount >= 0.5 {
                to
            } else {
                from
            }
        }
    }
}

fn lerp_channel(from: u8, to: u8, amount: f32) -> u8 {
    let from = f32::from(from);
    let to = f32::from(to);
    (from + (to - from) * amount).round().clamp(0.0, 255.0) as u8
}

// ---------------------------------------------------------------------------
// Kitty graphics capability receipt. No launch image is transmitted.
// ---------------------------------------------------------------------------

/// Capability query: a 1×1 RGB image sent with `a=q` is validated but never
/// stored; a supporting terminal answers `ESC _ G i=31;OK ESC \`.
const KITTY_QUERY: &[u8] = b"\x1b_Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA\x1b\\";
/// A terminal that supports the protocol answers within a millisecond.
const KITTY_QUERY_TIMEOUT: std::time::Duration = std::time::Duration::from_millis(120);

static KITTY_GRAPHICS: OnceLock<bool> = OnceLock::new();

/// Environments worth asking. The query is only issued where the terminal is
/// one that could answer, so terminals that will never reply do not pay the
/// timeout at startup. tmux is excluded: image data needs a passthrough
/// wrapper there, which this tier does not do.
fn kitty_candidate_env(env: impl Fn(&str) -> Option<String>) -> bool {
    if env("TMUX").is_some() {
        return false;
    }
    let term = env("TERM").unwrap_or_default().to_ascii_lowercase();
    let program = env("TERM_PROGRAM").unwrap_or_default().to_ascii_lowercase();
    term.contains("kitty")
        || term.contains("ghostty")
        || matches!(
            program.as_str(),
            "kitty" | "wezterm" | "ghostty" | "konsole"
        )
        || env("KITTY_WINDOW_ID").is_some()
        || env("KONSOLE_VERSION").is_some()
}

/// The terminal's answer to the capability query, decided: `OK` means it
/// validated our image; anything else (an error, no reply) does not.
fn kitty_query_accepted(reply: Option<&[u8]>) -> bool {
    reply.is_some_and(|reply| {
        let text = String::from_utf8_lossy(reply);
        text.contains("_G") && text.contains(";OK")
    })
}

/// Ask the terminal once whether it draws kitty graphics, and cache the
/// answer for the process. Call from the TUI entry point in the same window
/// as `codewhale_palette::probe_terminal_background` — raw mode on, event loop not yet
/// reading stdin — since the reply comes back on stdin.
pub fn probe_kitty_graphics() -> bool {
    *KITTY_GRAPHICS.get_or_init(|| {
        kitty_candidate_env(|key| std::env::var(key).ok())
            && kitty_query_accepted(
                codewhale_palette::osc11::query_terminal(KITTY_QUERY, KITTY_QUERY_TIMEOUT)
                    .as_deref(),
            )
    })
}

/// Whether the terminal reported graphics support; false before the probe runs.
#[must_use]
pub fn kitty_graphics_supported() -> bool {
    KITTY_GRAPHICS.get().copied().unwrap_or(false)
}

// ---------------------------------------------------------------------------
// Sixel graphics tier.
//
// For terminals that draw sixel (foot, mlterm, contour, sixel-enabled xterm,
// WezTerm with kitty graphics off) but never answered the kitty query.
// Keep the capability probe for the terminal receipt; launch has no sixel renderer.
// ---------------------------------------------------------------------------

/// Primary device-attributes request. A sixel terminal answers with its
/// capability parameters, e.g. `ESC [ ? 62 ; 4 c` (foot) or
/// `ESC [ ? 63 ; 1 ; 2 ; 4 ; 6 ; 7 ; 15 ; 18 c` (xterm-sixel); parameter 4 is
/// sixel graphics. Read with `query_terminal_csi`: a DA reply ends at its
/// `c` final byte, not at BEL/ST, so the shared OSC-11 reader would swallow
/// following input waiting for a terminator that never comes.
const SIXEL_QUERY: &[u8] = b"\x1b[c";
/// Same budget as the kitty query: answering terminals reply at once.
const SIXEL_QUERY_TIMEOUT: std::time::Duration = std::time::Duration::from_millis(120);
static SIXEL_GRAPHICS: OnceLock<bool> = OnceLock::new();

/// Environments worth asking. Same contract as the kitty gate: only
/// terminals that answer a DA query promptly, never tmux (image data needs
/// a passthrough wrapper there, which this tier does not do). The DA reply
/// itself decides — `xterm-256color` is listed because Terminal.app, iTerm2
/// and xterm.js answer it at once without parameter 4, which is a fast no.
fn sixel_candidate_env(env: impl Fn(&str) -> Option<String>) -> bool {
    if env("TMUX").is_some() {
        return false;
    }
    let term = env("TERM").unwrap_or_default().to_ascii_lowercase();
    let program = env("TERM_PROGRAM").unwrap_or_default().to_ascii_lowercase();
    term.contains("foot")
        || term.contains("mlterm")
        || term.contains("contour")
        || term == "xterm"
        || term.starts_with("xterm-")
        || term == "st"
        || term.starts_with("st-")
        || program.as_str() == "wezterm"
}

/// The terminal's answer to the primary-DA query, decided: parameter `4`
/// (sixel graphics) present means it draws sixel; anything else does not.
fn da_reports_sixel(reply: Option<&[u8]>) -> bool {
    let Some(reply) = reply else {
        return false;
    };
    let text = String::from_utf8_lossy(reply);
    text.split('\x1b').any(|chunk| {
        let body = chunk.strip_prefix("[?").or_else(|| chunk.strip_prefix("["));
        body.is_some_and(|body| {
            body.strip_suffix('c')
                .is_some_and(|params| params.split(';').any(|param| param == "4"))
        })
    })
}

/// Ask the terminal once whether it draws sixel, and cache the answer for
/// the process. Call after [`probe_kitty_graphics`] in the same pre-loop
/// window (raw mode on, event loop not yet reading stdin). A positive kitty
/// result skips this fallback diagnostic probe; neither probe paints an image.
pub fn probe_sixel_graphics() -> bool {
    *SIXEL_GRAPHICS.get_or_init(|| {
        !kitty_graphics_supported()
            && sixel_candidate_env(|key| std::env::var(key).ok())
            && da_reports_sixel(
                codewhale_palette::osc11::query_terminal_csi(SIXEL_QUERY, SIXEL_QUERY_TIMEOUT)
                    .as_deref(),
            )
    })
}

#[cfg(test)]
mod tests {
    #[test]
    fn launch_reveal_preserves_width_and_only_adds_canonical_dots() {
        use unicode_width::UnicodeWidthStr;
        for size in [
            super::MarkSize::Large,
            super::MarkSize::Small,
            super::MarkSize::Tiny,
        ] {
            for row in size.rows() {
                let mut previous = super::reveal_row(row, 0, true);
                for elapsed in [60, 140, 240, 360, 1000] {
                    let next = super::reveal_row(row, elapsed, true);
                    assert_eq!(next.width(), row.width());
                    for ((old, new), canonical) in
                        previous.chars().zip(next.chars()).zip(row.chars())
                    {
                        if ('\u{2800}'..='\u{28ff}').contains(&canonical) {
                            let old = u32::from(old) - 0x2800;
                            let new = u32::from(new) - 0x2800;
                            let target = u32::from(canonical) - 0x2800;
                            assert_eq!(old & new, old);
                            assert_eq!(new & target, new);
                        }
                    }
                    previous = next;
                }
                assert_eq!(previous, *row);
                assert_eq!(super::reveal_row(row, 0, false), *row);
            }
        }
    }

    use super::*;

    #[test]
    fn kitty_candidates_are_the_terminals_that_can_answer_and_never_tmux() {
        let env = |vars: &[(&str, &str)]| {
            let vars: Vec<(String, String)> = vars
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |key: &str| vars.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone())
        };
        assert!(kitty_candidate_env(env(&[("TERM", "xterm-kitty")])));
        assert!(kitty_candidate_env(env(&[("TERM_PROGRAM", "WezTerm")])));
        assert!(kitty_candidate_env(env(&[("TERM", "xterm-ghostty")])));
        assert!(kitty_candidate_env(env(&[("KONSOLE_VERSION", "230800")])));
        assert!(!kitty_candidate_env(env(&[
            ("TERM", "xterm-256color"),
            ("TERM_PROGRAM", "Apple_Terminal")
        ])));
        assert!(!kitty_candidate_env(env(&[
            ("TERM", "xterm-kitty"),
            ("TMUX", "/tmp/tmux-501/default,1,0")
        ])));
    }

    #[test]
    fn the_query_is_accepted_only_on_an_ok_reply() {
        assert!(kitty_query_accepted(Some(b"\x1b_Gi=31;OK")));
        assert!(!kitty_query_accepted(Some(b"\x1b_Gi=31;EINVAL:bad")));
        assert!(!kitty_query_accepted(Some(b"\x1b[?1;2c")));
        assert!(!kitty_query_accepted(None));
    }

    #[test]
    fn sixel_candidates_are_the_terminals_that_answer_da_and_never_tmux() {
        let env = |vars: &[(&str, &str)]| {
            let vars: Vec<(String, String)> = vars
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |key: &str| vars.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone())
        };
        assert!(sixel_candidate_env(env(&[("TERM", "foot")])));
        assert!(sixel_candidate_env(env(&[("TERM", "foot-extra")])));
        assert!(sixel_candidate_env(env(&[("TERM", "mlterm")])));
        assert!(sixel_candidate_env(env(&[("TERM", "contour")])));
        // `xterm-256color` is a candidate even though most of its owners
        // decline: Terminal.app, iTerm2 and xterm.js answer DA at once
        // without parameter 4, which is a fast no rather than a timeout.
        assert!(sixel_candidate_env(env(&[("TERM", "xterm-256color")])));
        assert!(sixel_candidate_env(env(&[("TERM", "st-256color")])));
        assert!(sixel_candidate_env(env(&[("TERM_PROGRAM", "WezTerm")])));
        assert!(!sixel_candidate_env(env(&[])));
        assert!(!sixel_candidate_env(env(&[("TERM", "dumb")])));
        assert!(!sixel_candidate_env(env(&[
            ("TERM", "foot"),
            ("TMUX", "/tmp/tmux-501/default,1,0")
        ])));
    }

    #[test]
    fn the_da_reply_decides_on_parameter_four_only() {
        // foot: sixel present.
        assert!(da_reports_sixel(Some(b"\x1b[?62;4c")));
        // xterm-sixel: sixel among other capabilities.
        assert!(da_reports_sixel(Some(b"\x1b[?63;1;2;4;6;7;15;18c")));
        // Plain xterm: answers, no sixel.
        assert!(!da_reports_sixel(Some(b"\x1b[?62;1;2;6;7c")));
        // A 4 inside another parameter is not sixel.
        assert!(!da_reports_sixel(Some(b"\x1b[?62;44c")));
        // A kitty reply is not a DA reply.
        assert!(!da_reports_sixel(Some(b"\x1b_Gi=31;OK\x1b\\")));
        assert!(!da_reports_sixel(None));
    }
}
