//! The Codewhale mark — `brand/mark.svg` in braille dots (2×4 per cell).
//!
//! The rows are generated, never hand-drawn: `scripts/brand/braille-mark.py`
//! (density 400, threshold 0.3, aspect preserved and centred in the design's
//! box, all-blank edge columns trimmed, the eye carved as one cleared dot).
//! Shell design §2.0 item 4: "the mark is the real logo, in dots." Two rungs
//! from the design's boxes: [`MarkSize::Small`] (box 11×3 → ink 7×3) and
//! [`MarkSize::Tiny`] (box 8×2 → ink 5×2). The ASCII lane has no mark at all:
//! `glyphs::ascii_fallback` flattens braille to `#`, so the wordmark line
//! stands alone there.
//!
//! Two paint tiers share one motion:
//!
//! - [`render_mark`] paints the braille rows (every terminal).
//! - On terminals that answer the kitty graphics query
//!   ([`probe_kitty_graphics`]) the launch header paints
//!   [`render_kitty_placeholders`] instead: Unicode placeholder cells the
//!   terminal replaces with the PNG transmitted once by
//!   [`transmit_kitty_mark`]. ratatui's buffer still owns the cells, so the
//!   image survives redraws.
//!
//! Motion ("surfacing", founder 2026-09-01): over `MARK_SURFACE_MS` the mark
//! reveals from the bottom of its box upward — the whale rises out of the
//! field — while its colour lerps from the field to the accent through
//! [`surface_progress`]'s raised-cosine ease. Then it holds still forever.
//! Reduced motion passes `progress = 1.0`, which is this same drawing at its
//! endpoint, so the still frame cannot drift from the animated one.

use std::io::Write;
use std::sync::OnceLock;

use ratatui::{buffer::Buffer, layout::Rect, style::Color, style::Style};

/// Rungs of the mark's scale ladder, each generated at its own box.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MarkSize {
    /// Box 11×3, ink 7×3 — the launch header's mark.
    Small,
    /// Box 8×2, ink 5×2 — for stages too narrow for the header lines beside
    /// the small rung.
    Tiny,
}

// generated by scripts/brand/braille-mark.py from brand/mark.svg
// (density 400, glyph bbox 1990x1780px, threshold 0.3, aspect preserved,
// edge columns trimmed, eye carved)

// SMALL: box 11x3 -> ink 7x3
const SMALL_ROWS: [&str; 3] = [
    "⣠⡾⠛⠷⠄  ", //
    "⣿⣄⣠⣤⣶⠶⡆",
    "⠙⠿⣯⣿⡡⠞ ",
];

// TINY: box 8x2 -> ink 5x2
const TINY_ROWS: [&str; 2] = [
    "⢠⡞⠛⢂⣀", //
    "⠘⢿⣻⣟⠝",
];

impl MarkSize {
    /// Cell footprint as `(cols, rows)` — the ink's, not the design box's.
    #[must_use]
    pub const fn cells(self) -> (u16, u16) {
        match self {
            Self::Small => (7, 3),
            Self::Tiny => (5, 2),
        }
    }

    /// The braille rows for this rung. Blank cells are spaces so the
    /// renderer leaves the field behind them untouched.
    #[must_use]
    pub const fn rows(self) -> &'static [&'static str] {
        match self {
            Self::Small => &SMALL_ROWS,
            Self::Tiny => &TINY_ROWS,
        }
    }
}

/// Blend `from` toward `to` (0.0 → `from`, 1.0 → `to`). At 0 the mark is
/// exactly the field colour, so it rises out of the water rather than over it.
#[must_use]
pub fn lerp_color(from: Color, to: Color, amount: f32) -> Color {
    let amount = amount.clamp(0.0, 1.0);
    match (from, to) {
        (Color::Rgb(fr, fg, fb), Color::Rgb(tr, tg, tb)) => Color::Rgb(
            lerp_channel(fr, tr, amount),
            lerp_channel(fg, tg, amount),
            lerp_channel(fb, tb, amount),
        ),
        // Indexed colours have no channels to interpolate; snap at midpoint.
        _ => {
            if amount >= 0.5 {
                to
            } else {
                from
            }
        }
    }
}

fn lerp_channel(from: u8, to: u8, amount: f32) -> u8 {
    let from = f32::from(from);
    let to = f32::from(to);
    (from + (to - from) * amount).round().clamp(0.0, 255.0) as u8
}

/// Raised-cosine rise over `duration_ms`, saturating at 1.0. Wall-clock keyed,
/// so a dropped frame costs smoothness, never correctness.
#[must_use]
pub fn surface_progress(elapsed_ms: u128, duration_ms: u128) -> f32 {
    if duration_ms == 0 || elapsed_ms >= duration_ms {
        return 1.0;
    }
    let t = elapsed_ms as f32 / duration_ms as f32;
    0.5 * (1.0 - (std::f32::consts::PI * t).cos())
}

/// Braille dot bits by dot row inside a cell (row 0 = top): dots 1/4, 2/5,
/// 3/6, then 7/8 on the bottom row.
const DOT_ROW_BITS: [u32; 4] = [0x01 | 0x08, 0x02 | 0x10, 0x04 | 0x20, 0x40 | 0x80];

/// The dot bits of a braille glyph; `None` for anything outside U+2800..=U+28FF.
fn braille_bits(glyph: char) -> Option<u32> {
    let code = u32::from(glyph);
    (0x2800..=0x28FF).contains(&code).then(|| code - 0x2800)
}

/// How many dot rows (from the bottom) of a `total`-dot-row mark are shown
/// at `progress`. `0.0` shows nothing, `1.0` shows every row; the reveal is
/// monotonic so a frame never un-surfaces.
fn revealed_dot_rows(progress: f32, total: u32) -> u32 {
    ((progress.clamp(0.0, 1.0) * total as f32).ceil() as u32).min(total)
}

/// Paint the braille mark with its top-left corner at `area`'s origin, in
/// `ink`, surfacing out of `field`. `progress` is `[0,1]`: the box reveals
/// dot row by dot row from the bottom while the colour lerps field → ink.
/// Returns the painted rect, or a zero-width rect when the area is too small
/// (the mark declines rather than clipping).
pub fn render_mark(
    area: Rect,
    buf: &mut Buffer,
    size: MarkSize,
    ink: Color,
    field: Color,
    progress: f32,
) -> Rect {
    let rows = size.rows();
    let (cols, row_count) = size.cells();
    if area.width < cols || area.height < row_count {
        return Rect::new(area.x, area.y, 0, 0);
    }
    let total_dot_rows = u32::from(row_count) * 4;
    let first_visible = total_dot_rows - revealed_dot_rows(progress, total_dot_rows);
    let color = lerp_color(field, ink, progress);
    for (index, line) in rows.iter().enumerate() {
        let y = area.y + index as u16;
        let mask = DOT_ROW_BITS
            .iter()
            .enumerate()
            .filter(|(dot_row, _)| (index as u32) * 4 + *dot_row as u32 >= first_visible)
            .fold(0u32, |mask, (_, bits)| mask | bits);
        if mask == 0 {
            continue;
        }
        for (x, glyph) in (area.x..).zip(line.chars()) {
            if x >= area.right() {
                break;
            }
            // Blanks (and fully-masked cells) are skipped, not painted: they
            // must not erase the field behind them.
            let bits = braille_bits(glyph).map_or(0, |bits| bits & mask);
            if bits == 0 {
                continue;
            }
            if let Some(cell) = buf.cell_mut((x, y)) {
                let glyph = char::from_u32(0x2800 | bits).expect("braille block is contiguous");
                cell.set_symbol(&glyph.to_string());
                cell.set_style(Style::default().fg(color));
            }
        }
    }
    Rect::new(area.x, area.y, cols, row_count)
}

// ---------------------------------------------------------------------------
// Kitty graphics tier.
//
// Protocol: https://sw.kovidgoyal.net/kitty/graphics-protocol/ — the image is
// transmitted once as base64 PNG chunks (`a=T,f=100`), given a *virtual*
// placement (`a=p,U=1`) sized in cells, and then shown wherever the screen
// holds placeholder cells: U+10EEEE with the image id in the foreground
// colour and the row/column encoded as combining diacritics. Those are
// ordinary cells to ratatui, so the diff, the alternate screen and redraws
// all keep the image where the buffer says it is.
// ---------------------------------------------------------------------------

/// Image id of the mark. Kept ≤ 255 so the placeholder foreground is an
/// indexed colour, which every palette-adaptation stage leaves untouched
/// (only RGB foregrounds are theme-remapped or contrast-lifted).
pub const KITTY_MARK_IMAGE_ID: u8 = 31;
/// The placeholder block: a cell is about 1:2, so 6×3 is square like the PNG.
pub const KITTY_MARK_COLS: u16 = 6;
pub const KITTY_MARK_ROWS: u16 = 3;
/// Cell heights from here up get the 96 px raster; smaller cells get 48 px.
const KITTY_LARGE_CELL_PX: u16 = 24;

const MARK_PNG_96: &[u8] = include_bytes!("../../assets/mark-96.png");
const MARK_PNG_48: &[u8] = include_bytes!("../../assets/mark-48.png");

/// The placeholder character itself.
const PLACEHOLDER: char = '\u{10EEEE}';
/// Row/column diacritics, in protocol order: index `i` encodes `i`.
const PLACEHOLDER_DIACRITICS: [char; 16] = [
    '\u{0305}', '\u{030D}', '\u{030E}', '\u{0310}', '\u{0312}', '\u{033D}', '\u{033E}', '\u{033F}',
    '\u{0346}', '\u{034A}', '\u{034B}', '\u{034C}', '\u{0350}', '\u{0351}', '\u{0352}', '\u{0357}',
];

/// Capability query: a 1×1 RGB image sent with `a=q` is validated but never
/// stored; a supporting terminal answers `ESC _ G i=31;OK ESC \`.
const KITTY_QUERY: &[u8] = b"\x1b_Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA\x1b\\";
/// A terminal that supports the protocol answers within a millisecond.
const KITTY_QUERY_TIMEOUT: std::time::Duration = std::time::Duration::from_millis(120);
/// Base64 payload per chunk (the protocol's maximum is 4096).
const KITTY_CHUNK: usize = 4096;

static KITTY_GRAPHICS: OnceLock<bool> = OnceLock::new();

/// Environments worth asking. The query is only issued where the terminal is
/// one that could answer, so terminals that will never reply do not pay the
/// timeout at startup. tmux is excluded: image data needs a passthrough
/// wrapper there, which this tier does not do.
fn kitty_candidate_env(env: impl Fn(&str) -> Option<String>) -> bool {
    if env("TMUX").is_some() {
        return false;
    }
    let term = env("TERM").unwrap_or_default().to_ascii_lowercase();
    let program = env("TERM_PROGRAM").unwrap_or_default().to_ascii_lowercase();
    term.contains("kitty")
        || term.contains("ghostty")
        || matches!(
            program.as_str(),
            "kitty" | "wezterm" | "ghostty" | "konsole"
        )
        || env("KITTY_WINDOW_ID").is_some()
        || env("KONSOLE_VERSION").is_some()
}

/// The terminal's answer to the capability query, decided: `OK` means it
/// validated our image; anything else (an error, no reply) does not.
fn kitty_query_accepted(reply: Option<&[u8]>) -> bool {
    reply.is_some_and(|reply| {
        let text = String::from_utf8_lossy(reply);
        text.contains("_G") && text.contains(";OK")
    })
}

/// Ask the terminal once whether it draws kitty graphics, and cache the
/// answer for the process. Call from the TUI entry point in the same window
/// as `palette::probe_terminal_background` — raw mode on, event loop not yet
/// reading stdin — since the reply comes back on stdin.
pub fn probe_kitty_graphics() -> bool {
    *KITTY_GRAPHICS.get_or_init(|| {
        kitty_candidate_env(|key| std::env::var(key).ok())
            && kitty_query_accepted(
                crate::palette::osc11::query_terminal(KITTY_QUERY, KITTY_QUERY_TIMEOUT).as_deref(),
            )
    })
}

/// Whether the probe said yes. `false` before the probe runs, so a render
/// that outruns startup paints the braille tier rather than empty cells.
#[must_use]
pub fn kitty_graphics_supported() -> bool {
    KITTY_GRAPHICS.get().copied().unwrap_or(false)
}

/// The byte stream that transmits `png` as image `id` and gives it a virtual
/// placement `cols`×`rows` cells. `q=2` silences the terminal's replies so
/// nothing lands in the input stream.
#[must_use]
pub fn kitty_transmit_sequence(png: &[u8], id: u8, cols: u16, rows: u16) -> Vec<u8> {
    use base64::{Engine as _, engine::general_purpose::STANDARD};
    let encoded = STANDARD.encode(png);
    let chunks: Vec<&[u8]> = encoded.as_bytes().chunks(KITTY_CHUNK).collect();
    let mut out = Vec::with_capacity(encoded.len() + 64 * chunks.len());
    for (index, chunk) in chunks.iter().enumerate() {
        let more = u8::from(index + 1 < chunks.len());
        if index == 0 {
            out.extend_from_slice(format!("\x1b_Ga=T,f=100,q=2,i={id},m={more};").as_bytes());
        } else {
            out.extend_from_slice(format!("\x1b_Gm={more};").as_bytes());
        }
        out.extend_from_slice(chunk);
        out.extend_from_slice(b"\x1b\\");
    }
    out.extend_from_slice(format!("\x1b_Ga=p,U=1,q=2,i={id},c={cols},r={rows}\x1b\\").as_bytes());
    out
}

/// The byte stream that deletes image `id` and frees its data (`d=I`).
#[must_use]
pub fn kitty_delete_sequence(id: u8) -> Vec<u8> {
    format!("\x1b_Ga=d,d=I,q=2,i={id}\x1b\\").into_bytes()
}

/// Pick the raster for the terminal's cell height (`None` → the large one).
fn kitty_mark_png(cell_height_px: Option<u16>) -> &'static [u8] {
    match cell_height_px {
        Some(px) if px < KITTY_LARGE_CELL_PX => MARK_PNG_48,
        _ => MARK_PNG_96,
    }
}

/// Transmit the mark once, if the probe said the terminal draws it. Cheap
/// no-op otherwise. Write errors are logged, never fatal: a mark that fails
/// to upload simply leaves the placeholder cells blank until the next paint
/// falls back to braille.
pub fn transmit_kitty_mark<W: Write>(writer: &mut W, cell_height_px: Option<u16>) {
    if !kitty_graphics_supported() {
        return;
    }
    let bytes = kitty_transmit_sequence(
        kitty_mark_png(cell_height_px),
        KITTY_MARK_IMAGE_ID,
        KITTY_MARK_COLS,
        KITTY_MARK_ROWS,
    );
    if let Err(err) = writer.write_all(&bytes).and_then(|()| writer.flush()) {
        tracing::debug!(target: "kitty_graphics", ?err, "mark transmission failed");
    }
}

/// Delete the transmitted mark on the way out so the terminal frees it.
pub fn delete_kitty_mark<W: Write>(writer: &mut W) {
    if !kitty_graphics_supported() {
        return;
    }
    let bytes = kitty_delete_sequence(KITTY_MARK_IMAGE_ID);
    if let Err(err) = writer.write_all(&bytes).and_then(|()| writer.flush()) {
        tracing::debug!(target: "kitty_graphics", ?err, "mark deletion failed");
    }
}

/// One placeholder cell's symbol: the placeholder plus its row and column
/// diacritics.
#[must_use]
pub fn kitty_placeholder_symbol(row: u16, col: u16) -> String {
    let row = PLACEHOLDER_DIACRITICS[usize::from(row) % PLACEHOLDER_DIACRITICS.len()];
    let col = PLACEHOLDER_DIACRITICS[usize::from(col) % PLACEHOLDER_DIACRITICS.len()];
    format!("{PLACEHOLDER}{row}{col}")
}

/// Paint the `KITTY_MARK_COLS`×`KITTY_MARK_ROWS` placeholder block with its
/// top-left corner at `area`'s origin. Same surfacing as [`render_mark`], at
/// cell granularity: rows appear from the bottom as `progress` rises. Returns
/// the block's rect, or a zero-width rect when it does not fit.
pub fn render_kitty_placeholders(area: Rect, buf: &mut Buffer, progress: f32) -> Rect {
    if area.width < KITTY_MARK_COLS || area.height < KITTY_MARK_ROWS {
        return Rect::new(area.x, area.y, 0, 0);
    }
    let first_visible =
        u32::from(KITTY_MARK_ROWS) - revealed_dot_rows(progress, u32::from(KITTY_MARK_ROWS));
    for row in 0..KITTY_MARK_ROWS {
        if u32::from(row) < first_visible {
            continue;
        }
        for col in 0..KITTY_MARK_COLS {
            if let Some(cell) = buf.cell_mut((area.x + col, area.y + row)) {
                cell.set_symbol(&kitty_placeholder_symbol(row, col));
                cell.set_style(Style::default().fg(Color::Indexed(KITTY_MARK_IMAGE_ID)));
            }
        }
    }
    Rect::new(area.x, area.y, KITTY_MARK_COLS, KITTY_MARK_ROWS)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_rung_matches_its_declared_footprint_in_braille_only() {
        for size in [MarkSize::Small, MarkSize::Tiny] {
            let (cols, rows) = size.cells();
            let art = size.rows();
            assert_eq!(art.len(), usize::from(rows), "{size:?} row count");
            for line in art {
                assert_eq!(
                    line.chars().count(),
                    usize::from(cols),
                    "{size:?} row {line:?} is not {cols} cells"
                );
                for glyph in line.chars() {
                    assert!(
                        glyph == ' ' || braille_bits(glyph).is_some(),
                        "{size:?} row {line:?} holds a non-braille glyph {glyph:?}"
                    );
                }
            }
            // Generated rows are trimmed: the first and last columns carry ink.
            assert!(art.iter().any(|line| line.starts_with(|c| c != ' ')));
            assert!(art.iter().any(|line| line.ends_with(|c| c != ' ')));
        }
    }

    #[test]
    fn the_mark_has_an_eye() {
        // The script carves the eye as one cleared dot inside the body; at
        // the small rung it is the `⣯` cell (dot 5 missing from a full cell).
        assert!(
            SMALL_ROWS.iter().any(|line| line.contains('⣯')),
            "small rung lost its eye"
        );
    }

    #[test]
    fn surface_progress_is_a_monotonic_rise_that_settles_at_one() {
        assert!((surface_progress(0, 640) - 0.0).abs() < 1e-6);
        assert!((surface_progress(320, 640) - 0.5).abs() < 1e-3);
        assert!((surface_progress(640, 640) - 1.0).abs() < 1e-6);
        assert!((surface_progress(5_000, 640) - 1.0).abs() < 1e-6);
        let mut previous = -1.0;
        for ms in (0..=640).step_by(20) {
            let value = surface_progress(ms, 640);
            assert!(value >= previous, "regressed at {ms}ms");
            previous = value;
        }
    }

    #[test]
    fn a_zero_length_rise_is_settled_not_divided_by_zero() {
        assert!((surface_progress(0, 0) - 1.0).abs() < 1e-6);
    }

    #[test]
    fn the_mark_emerges_from_the_field_rather_than_fading_over_it() {
        let field = Color::Rgb(3, 7, 13);
        let gold = Color::Rgb(246, 196, 83);
        assert_eq!(lerp_color(field, gold, 0.0), field);
        assert_eq!(lerp_color(field, gold, 1.0), gold);
        let mid = lerp_color(field, gold, 0.5);
        assert_eq!(mid, Color::Rgb(125, 102, 48));
    }

    fn tilde_buffer(width: u16, height: u16) -> Buffer {
        let mut buf = Buffer::empty(Rect::new(0, 0, width, height));
        for x in 0..width {
            for y in 0..height {
                if let Some(cell) = buf.cell_mut((x, y)) {
                    cell.set_symbol("~");
                }
            }
        }
        buf
    }

    #[test]
    fn render_anchors_top_left_and_leaves_blanks_untouched() {
        let area = Rect::new(2, 1, 12, 5);
        let mut buf = tilde_buffer(14, 6);
        let painted = render_mark(
            area,
            &mut buf,
            MarkSize::Small,
            Color::Rgb(246, 196, 83),
            Color::Rgb(3, 7, 13),
            1.0,
        );
        assert_eq!(painted, Rect::new(2, 1, 7, 3));
        // Row 0 is `⣠⡾⠛⠷⠄  `: ink at the origin, trailing blanks keep the field.
        assert_eq!(buf.cell((1, 1)).map(|c| c.symbol()), Some("~"));
        assert_eq!(buf.cell((2, 1)).map(|c| c.symbol()), Some("⣠"));
        assert_eq!(buf.cell((7, 1)).map(|c| c.symbol()), Some("~"));
        assert_eq!(buf.cell((8, 1)).map(|c| c.symbol()), Some("~"));
        // Row 1 is full width: its last cell is ink.
        assert_eq!(buf.cell((8, 2)).map(|c| c.symbol()), Some("⡆"));
        assert_eq!(buf.cell((9, 2)).map(|c| c.symbol()), Some("~"));
    }

    #[test]
    fn the_mark_surfaces_from_the_bottom_dot_row_by_dot_row() {
        let ink = Color::Rgb(246, 196, 83);
        let field = Color::Rgb(3, 7, 13);
        let area = Rect::new(0, 0, 7, 3);
        // Nothing has surfaced at 0.
        let mut buf = tilde_buffer(7, 3);
        render_mark(area, &mut buf, MarkSize::Small, ink, field, 0.0);
        assert!((0..7).all(|x| (0..3).all(|y| buf[(x, y)].symbol() == "~")));
        // Half way: the bottom six dot rows only — the top cell row is still
        // under water, and the middle row shows only its lower half.
        let mut buf = tilde_buffer(7, 3);
        render_mark(area, &mut buf, MarkSize::Small, ink, field, 0.5);
        assert!(
            (0..7).all(|x| buf[(x, 0)].symbol() == "~"),
            "top row submerged"
        );
        let middle: u32 = (0..7)
            .filter_map(|x| buf[(x, 1)].symbol().chars().next())
            .filter_map(braille_bits)
            .fold(0, |acc, bits| acc | bits);
        assert_ne!(middle, 0, "middle row is partly up");
        assert_eq!(
            middle & (DOT_ROW_BITS[0] | DOT_ROW_BITS[1]),
            0,
            "the middle row's upper dots are still submerged"
        );
        // Settled: identical to a direct 1.0 paint, and fully the ink colour.
        let mut buf = tilde_buffer(7, 3);
        render_mark(area, &mut buf, MarkSize::Small, ink, field, 1.0);
        for (y, line) in SMALL_ROWS.iter().enumerate() {
            for (x, glyph) in line.chars().enumerate() {
                let cell = &buf[(x as u16, y as u16)];
                if glyph == ' ' {
                    assert_eq!(cell.symbol(), "~");
                } else {
                    assert_eq!(cell.symbol(), glyph.to_string());
                    assert_eq!(cell.fg, ink);
                }
            }
        }
    }

    #[test]
    fn render_declines_rather_than_clipping_when_the_area_is_too_small() {
        let area = Rect::new(0, 0, 6, 3);
        let mut buf = Buffer::empty(area);
        let painted = render_mark(
            area,
            &mut buf,
            MarkSize::Small,
            Color::Rgb(246, 196, 83),
            Color::Rgb(3, 7, 13),
            1.0,
        );
        assert_eq!(painted.width, 0);
        assert_eq!(buf.cell((0, 0)).map(|c| c.symbol()), Some(" "));
    }

    #[test]
    fn kitty_candidates_are_the_terminals_that_can_answer_and_never_tmux() {
        let env = |vars: &[(&str, &str)]| {
            let vars: Vec<(String, String)> = vars
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |key: &str| vars.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone())
        };
        assert!(kitty_candidate_env(env(&[("TERM", "xterm-kitty")])));
        assert!(kitty_candidate_env(env(&[("TERM_PROGRAM", "WezTerm")])));
        assert!(kitty_candidate_env(env(&[("TERM", "xterm-ghostty")])));
        assert!(kitty_candidate_env(env(&[("KONSOLE_VERSION", "230800")])));
        assert!(!kitty_candidate_env(env(&[
            ("TERM", "xterm-256color"),
            ("TERM_PROGRAM", "Apple_Terminal")
        ])));
        assert!(!kitty_candidate_env(env(&[
            ("TERM", "xterm-kitty"),
            ("TMUX", "/tmp/tmux-501/default,1,0")
        ])));
    }

    #[test]
    fn the_query_is_accepted_only_on_an_ok_reply() {
        assert!(kitty_query_accepted(Some(b"\x1b_Gi=31;OK")));
        assert!(!kitty_query_accepted(Some(b"\x1b_Gi=31;EINVAL:bad")));
        assert!(!kitty_query_accepted(Some(b"\x1b[?1;2c")));
        assert!(!kitty_query_accepted(None));
    }

    #[test]
    fn the_transmit_stream_is_chunked_png_then_a_virtual_placement() {
        let bytes = kitty_transmit_sequence(MARK_PNG_96, 31, 6, 3);
        let text = String::from_utf8(bytes).expect("ASCII stream");
        let commands: Vec<&str> = text.split("\x1b\\").filter(|s| !s.is_empty()).collect();
        assert!(commands.len() >= 3, "{} commands", commands.len());
        assert!(commands[0].starts_with("\x1b_Ga=T,f=100,q=2,i=31,m=1;"));
        for chunk in &commands[..commands.len() - 1] {
            let payload = chunk.split_once(';').map(|(_, p)| p).unwrap_or("");
            assert!(
                payload.len() <= KITTY_CHUNK,
                "chunk over 4096: {}",
                payload.len()
            );
            assert!(
                payload
                    .bytes()
                    .all(|b| b.is_ascii_alphanumeric() || b == b'+' || b == b'/' || b == b'='),
                "chunk is not base64"
            );
        }
        let last_chunk = commands[commands.len() - 2];
        assert!(
            last_chunk.starts_with("\x1b_Gm=0;"),
            "final chunk ends the upload"
        );
        assert_eq!(
            commands[commands.len() - 1],
            "\x1b_Ga=p,U=1,q=2,i=31,c=6,r=3"
        );
        // The PNG really is one: decode the payload back.
        use base64::{Engine as _, engine::general_purpose::STANDARD};
        let payload: String = commands[..commands.len() - 1]
            .iter()
            .map(|chunk| chunk.split_once(';').map(|(_, p)| p).unwrap_or(""))
            .collect();
        let decoded = STANDARD.decode(payload).expect("base64 round-trips");
        assert_eq!(decoded, MARK_PNG_96);
        assert!(decoded.starts_with(b"\x89PNG"));
        assert_eq!(kitty_delete_sequence(31), b"\x1b_Ga=d,d=I,q=2,i=31\x1b\\");
    }

    #[test]
    fn the_bundled_rasters_decode_to_their_declared_sizes() {
        for (png, edge) in [(MARK_PNG_96, 96u32), (MARK_PNG_48, 48u32)] {
            let image = image::load_from_memory(png).expect("bundled mark decodes");
            assert_eq!((image.width(), image.height()), (edge, edge));
        }
        assert_eq!(kitty_mark_png(None), MARK_PNG_96);
        assert_eq!(kitty_mark_png(Some(16)), MARK_PNG_48);
        assert_eq!(kitty_mark_png(Some(32)), MARK_PNG_96);
    }

    #[test]
    fn placeholders_carry_the_image_id_and_their_own_coordinates() {
        let area = Rect::new(1, 0, 8, 4);
        let mut buf = tilde_buffer(9, 4);
        let painted = render_kitty_placeholders(area, &mut buf, 1.0);
        assert_eq!(painted, Rect::new(1, 0, 6, 3));
        let cell = &buf[(1u16, 0u16)];
        assert_eq!(cell.symbol(), "\u{10EEEE}\u{0305}\u{0305}");
        assert_eq!(cell.fg, Color::Indexed(KITTY_MARK_IMAGE_ID));
        assert_eq!(buf[(6u16, 2u16)].symbol(), "\u{10EEEE}\u{030E}\u{033D}");
        assert_eq!(buf[(7u16, 0u16)].symbol(), "~", "outside the block");
        assert_eq!(buf[(1u16, 3u16)].symbol(), "~", "below the block");
        // Surfacing at cell granularity: under a third of the way up, only
        // the bottom row is placed.
        let mut buf = tilde_buffer(9, 4);
        render_kitty_placeholders(area, &mut buf, 0.3);
        assert_eq!(buf[(1u16, 0u16)].symbol(), "~");
        assert_eq!(buf[(1u16, 1u16)].symbol(), "~");
        assert!(buf[(1u16, 2u16)].symbol().starts_with('\u{10EEEE}'));
    }
}
